var myHeading = document.querySeleactor('h1');
myHeading.innerHTML = 'Cloude server<br>2018-1!';
var text = 'This is a text.';
text = 10.5;
var a = 33.7;
var b = a*text;
var iceCream = 'chocolate';
var id =prompt('ID 입력', '');
alert(id + '가 로그인함.');
var passwordSystem = '12345';
var password = prompt('PW 입력', '');
if (password === passwordSystem) alert('정상 로그인!');
else alert('비밀번호 오류');